# Generated by Django 4.1.13 on 2024-05-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrepWiser', '0005_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
